export interface Character {
  items: Items;
}
export interface Items {
  head: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  neck: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  shoulder: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  back: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  chest: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  wrist: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  hands: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  waist: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  legs: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  feet: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  finger1: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  finger2: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  trinket1: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  trinket2: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  mainHand: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
  offHand: HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand;
}
export interface HeadOrNeckOrShoulderOrBackOrChestOrWristOrHandsOrWaistOrLegsOrFeetOrFinger1OrFinger2OrTrinket1OrTrinket2OrMainHandOrOffHand {
  id: number;
  name: string;
  stats?: (StatsEntity)[] | null;
  armor: number;
  bonusLists?: (number)[] | null;
}
export interface StatsEntity {
  stat: number;
  amount: number;
}
